branches:
  only:
    - master
    - /^(?!wip-).+$/
language: python
cache:
    pip: true
    directories:
        - $HOME/virtualenv/python2.7.12/lib/python2.7/site-packages
        - $HOME/virtualenv/python2.7.12/bin/
        - $HOME/unicorn
dist: trusty
sudo: required
os:
- linux
python:
- 2.7
install:
- travis_retry pip install -U pip
- travis_retry pip install --no-binary capstone --no-binary keystone-engine .[dev]
- scripts/travis_install_z3.sh
- scripts/travis_install_unicorn.sh 
script:
- scripts/travis_test.sh
notifications:
  slack:
    secure: cEBnjLHUGz1dBr0MRcvCN96ec8IAb6k53AAqovlhy2ogWzceBbEJ+k1B4q7blNAJutHpVzRe6poJdDnezXET1sibQebGVTPn3AonrAnDwfaPh7/2PFtdjIzKho8jXoAYmp9Dj6e1M/CUOPRBR54fDK47ljmJom6p5aKEOHjYnwMWjm8r0uixSst3VoWcRLxU+HQYnv1f+6ocZ3e1XoeJC7Etua6+9KSNL4l2qX1jfUqUv4rsB/6zLjo4FNmtq1J1UDa62cNH7O7tYmK0e+R8KDPaIJAgw2XRwwKLpFX5Z1DVttfLMUYN5tGj+uL1jiXFui6eAu3bJqDytGNZgDHf4kC3CgNXAuH8fG4MJAj5jgY4D85RzCrqN8eTs9ZgcEM9tOJ8VZDf4/X8m6+GysvrA9f3EkN7qx83XfdnY+6BLldH5Mus4U+m+xw8cjJRTe8lwovDKYTczh5pca9SkMFjbdxxQbkfynhwa3QSSmKtGKXE0HqoydbtaAy9Cl19JsCzJkJV8yqVyzvFbRSz63A1z8A0DxXgjfnvK1eki9hfHhUUuYs+b2/zha3qZvlwrNW4cC004kOHiOH8OpeUpWWhC3ht67Ox3mYZnig9glkwek6h6LRVdxLVn5HSUiZqDmxxTNsCeQLeX88LupWK7KvJk1J7H2wrBN9jZXN7Og7e1T4=
