dist: trusty
sudo: required
os:
  - linux
language: python
python:
  - 3.6.6

stages:
  - format
  - prepare
  - test
  - submit

env:
  global:
    - CC_TEST_REPORTER_ID=db72f1ed59628c16eb0c00cbcd629c4c71f68aa1892ef42d18c7c2b8326f460a
    - JOB_COUNT=4 # Three jobs generate test coverage: ethereum, ethereum_vm, native, and other
    - PYTHONWARNINGS="default::ResourceWarning" # Enable ResourceWarnings
  matrix:
    - TEST_TYPE=examples
    - TEST_TYPE=ethereum
    - TEST_TYPE=ethereum_vm
    - TEST_TYPE=native
    - TEST_TYPE=other

branches:
  only:
  - master
  - /^(?!wip-).+$/

cache:
  pip: true
  directories:
  - $HOME/virtualenv/python3.6.6/lib/python3.6/site-packages
  - $HOME/virtualenv/python3.6.6/bin/

jobs:
  include:
    - stage: format
      env: TEST_TYPE=format
      script:
        - black -t py36 --check .
    - stage: prepare
      env: TEST_TYPE=env
      script:
        - ./cc-test-reporter before-build
      after_success:
    - stage: submit
      env: TEST_TYPE=env
      script:
        - true
      after_script:
        - aws s3 sync "s3://manticore-testdata/coverage/$TRAVIS_COMMIT" coverage/ 
        - ./cc-test-reporter sum-coverage --output - --parts $JOB_COUNT coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -

install:
  - scripts/travis_install.sh $TEST_TYPE

script:
  - travis_wait 60 scripts/travis_test.sh $TEST_TYPE

after_success:
  - ./cc-test-reporter format-coverage -t coverage.py -o "coverage/codeclimate.$TEST_TYPE.json"
  - aws s3 sync coverage/ "s3://manticore-testdata/coverage/$TRAVIS_COMMIT"

